CREATE DATABASE DB_FACILITY;
USE DB_FACILITY;
DROP DATABASE DB_FACILITY;
-- 체육시설 TABLE
CREATE TABLE TBL_FACILITY(
	F_NO INT AUTO_INCREMENT,
	GUBUN VARCHAR(20) ,
	SVCID VARCHAR(200),
	MAXCLASSNM VARCHAR(20) ,	
	MINCLASSNM VARCHAR(20) ,
	SVCSTATNM VARCHAR(20) ,
	SVCNM VARCHAR(100) ,
	PAYATNM VARCHAR(20) ,
	PLACENM VARCHAR(20) ,
	USETGTINFO VARCHAR(20) ,
	SVCURL VARCHAR(100) ,
	X VARCHAR(20) ,
	Y VARCHAR(20) ,
	SVCOPNBGNDT VARCHAR(20) ,
	SVCOPNENDDT VARCHAR(20) ,
	RCPTBGNDT VARCHAR(20) ,
	RCPTENDDT VARCHAR(20) ,
	AREANM VARCHAR(20) ,
	IMGURL VARCHAR(1000) ,
	DTLCONT VARCHAR(10000) ,
	TELNO VARCHAR(20) ,
	V_MIN VARCHAR(20) ,
	V_MAX VARCHAR(20) ,
	REVSTDDAYNM VARCHAR(20) ,
	REVSTDDAY VARCHAR(20) ,
	PRIMARY KEY(F_NO)
);

DROP TABLE TBL_FACILITY;

SELECT * FROM TBL_FACILITY;